- name: Getting image from local registry for front
  docker_image:
    name: localhost:5000/frontimage
    repository: localhost:5000
    source: pull

- name: Run container for front image
  docker_container:
    name: movie-analyst-ui
    image: localhost:5000/frontimage
    state: started
    volumes:
    - "/etc/docker/movie-analyst-ui:/var/lib/movie-analyst-ui"
  published-ports:
    - "3030:3030"
  env: 
      BACKEND_URL: "35.164.156.112:3030"